import type { PortfolioItem } from "@/types";

export const CLOUD_ENGINEER_DIGITAL_WORLD_COVER_URL = "";

export const CLOUD_ENGINEER_DIGITAL_WORLD_DETAILED_BLOCKS: PortfolioItem[] = [
  {
    "id": "tpl-cloud-digital-text-0",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Value Proposition Document",
    "content":
      "I\u2019m super interested towards cloud technologies and I bring a unique blend of<strong> cloud engineering, AI/ML expertise, and academic research</strong> to Openchip.<br>My experience optimising Kubernetes deployments, securing cloud applications, and working with partner ecosystems positions me to make an immediate and valuable contribution to your team.",
    "templateSectionTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-1",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "How do I add value to the company?",
    "templateSectionTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-2",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Problem Statements",
    "templateSectionTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-page-card-3",
    "type": "page-card",
    "span": 6,
    "fontSize": "base",
    "title": "Cloud Orchestration",
    "content": "/images/vpd/Web3_talent_gap_22.webp",
    "showCoverImage": true,
    "mediaType": "image",
    "description": "<strong>Seamless Cloud Orchestration and Management of Openchip's RISC-V Chips</strong>",
    "height": 368,
    "detailedBlocks": [
      {
        "id": "tpl-cloud-digital-nested-3-0",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "I recognise that Openchip, as a developer of high-performance accelerator chips for HPC, AI/ML/DL, faces a significant challenge in ensuring these chips can be easily orchestrated and managed across various cloud environments. The need to deliver Kubernetes Device Plugins and extensions that effectively integrate with platforms like AKS, EKS, GKE, RedHat OpenShift, SUSE Rancher, and even lightweight Kubernetes distributions (K3s, MicroShift) is critical.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-1",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Here is how my solution would look like</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-2",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Development of Kubernetes Device Plugins and Extensions Optimised for RISC-V:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-3",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Optimisation of Workload Placement for HPC and AI/ML Workloads:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-4",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Analysis and Benchmarking:</strong> I would conduct a deep dive into the performance characteristics of Openchip's accelerators, focusing on HPC and AI/ML workloads. This will involve benchmarking various deployment scenarios and identifying bottlenecks.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-5",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Intelligent Scheduling:</strong> Based on my analysis, I would implement intelligent scheduling policies within Kubernetes. This involves:",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-6",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Strategic use of lightweight Kubernetes platforms:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-7",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "With the knowledge that Openchip has 56 partners from 14 countries for digital transformation and that lightweight Kubernetes platforms are the solution for the same, I would propose the use of MicroK8s since it provides a complete Kubernetes cluster that installs in under 60 seconds.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-8",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Ensuring Compatibility with Hybrid and Multi-Cloud Environments:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-9",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Platform Agnosticism:</strong> I would design the Kubernetes integrations to be as platform-agnostic as possible, avoiding vendor lock-in.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-10",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Infrastructure-as-Code (IaC):</strong> Leveraging tools like Terraform and AWS CloudFormation (which I have experience with), I would create reusable templates to quickly provision and configure cloud resources for Openchip's deployments across AWS, Azure, and Google Cloud.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-11",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Automation and CI/CD:</strong> I will implement CI/CD pipelines with Jenkins to automate the deployment and testing of Kubernetes configurations, ensuring consistency and repeatability across environments.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-12",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Leveraging My Existing Skills and Experiences</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-13",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Code Institute Experience:</strong> My experience at Code Institute, where I enhanced application deployment efficiency by 30% through Kubernetes and Docker, demonstrates my ability to optimise containerised applications and streamline deployment processes.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-14",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>MedTank AI Microservices:</strong> My work developing AI-driven micro-services at MedTank showcases my expertise in building scalable, cloud-native applications and integrating them into larger ecosystems.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-15",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Trinity College Research:</strong> My research experience at Trinity College Dublin, where I processed large datasets using cloud-based machine learning techniques, gives me a strong foundation for optimising HPC workloads on Openchip's accelerators.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-3-16",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Expected Outcomes</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
    ],
    "layoutRole": "halfCard",
  },
  {
    "id": "tpl-cloud-digital-page-card-4",
    "type": "page-card",
    "span": 6,
    "fontSize": "base",
    "title": "Observability & Monitoring",
    "content": "/images/vpd/Web3_talent_gap_23.webp",
    "showCoverImage": true,
    "mediaType": "image",
    "description": "<strong>Observability and Monitoring of Cloud Platforms</strong>",
    "height": 368,
    "detailedBlocks": [
      {
        "id": "tpl-cloud-digital-nested-4-0",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "I recognise that Openchip, as a developer of high-performance accelerator chips for HPC, AI/ML/DL, faces a significant challenge in ensuring these chips can be easily orchestrated and managed across various cloud environments. The need to deliver Kubernetes Device Plugins and extensions that effectively integrate with platforms like AKS, EKS, GKE, RedHat OpenShift, SUSE Rancher, and even lightweight Kubernetes distributions (K3s, MicroShift) is critical.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-1",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Here is how my solution would look like</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-2",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Implementation of a Comprehensive Observability Stack</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-3",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Focus on Key Performance Indicators (KPIs) for RISC-V Architectures</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-4",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Chip-Specific Metrics:</strong> I would collaborate with the hardware team to define metrics specific to the RISC-V chips, such as floating-point operations per second (FLOPS), AI inference throughput, and power consumption.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-5",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>HPC and AI/ML Metrics:</strong> Leveraging my experience with HPC and AI/ML environments, I'll create dashboards to track performance metrics relevant to these workloads, such as training time, model accuracy, and data processing rates.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-6",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>RAS-Specific Alerts:</strong> I would develop alerting rules to detect performance regressions, errors, and potential failures. Alerts will be configured to trigger based on specific thresholds and trends, ensuring that issues are caught early.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-7",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Proactive Anomaly Detection Using Machine Learning</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-8",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Anomaly Detection Models:</strong> Utilising my experience with AI/ML, I will explore using machine learning to develop anomaly detection models within the observability stack. This will involve:",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-9",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Predictive Maintenance:</strong> The machine learning models can also forecast future performance issues and trigger maintenance activities proactively, reducing downtime.<strong>Integrating Observability into CI/CD Pipelines</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-10",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Integrating Observability into CI/CD Pipelines</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-11",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Performance Testing:</strong> I will enhance the CI/CD pipelines to include automated performance testing.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-12",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Observability Validation:</strong> Before deploying new code, automated checks will verify that the changes do not introduce performance regressions or security vulnerabilities.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-4-13",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Expected Outcomes</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
    ],
    "layoutRole": "halfCard",
  },
  {
    "id": "tpl-cloud-digital-page-card-5",
    "type": "page-card",
    "span": 6,
    "fontSize": "base",
    "title": "Fleet Management Frameworks",
    "content": "/images/vpd/2596BE.webp",
    "showCoverImage": true,
    "mediaType": "image",
    "description": "<strong>Integrating with Fleet Management Frameworks and Partner Ecosystems</strong>",
    "height": 368,
    "detailedBlocks": [
      {
        "id": "tpl-cloud-digital-nested-5-0",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "I recognise that Openchip's success hinges on its ability to not only create innovative accelerator chips but also seamlessly integrate these chips into existing ecosystems. Integrating with fleet management frameworks and partner technologies (e.g., RedHat OpenShift, Canonical Kubernetes, SUSE Rancher, etc.) is essential for Openchip to reach its target audience and encourage widespread adoption of its RISC-V technology.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-1",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Here is how my solution would look like</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-2",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>API-First Design and Standardisation:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-3",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Strategic Partnerships and Collaboration:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-4",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Partner-Specific Integrations:</strong> Collaborate with key partners (RedHat, SUSE, Canonical, etc.) to develop integrations that leverage their specific platforms and ecosystems. For example, if working with RedHat OpenShift, I would focus on creating Operators that simplify the deployment and management of Openchip accelerators.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-5",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Ecosystem Support:</strong> I view my work as a means to bolster partnerships and enable Openchip\u2019s clients to become partners.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-6",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Kubernetes-Centric Approach:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-7",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Operators:</strong> As Kubernetes is a linchpin in cloud-native deployments, I'd prioritise developing Kubernetes Operators for Openchip\u2019s accelerators. Operators would automate deployment, configuration, scaling, and lifecycle management, reducing operational complexity.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-8",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Helm Charts:</strong> Creating pre-configured Helm charts will simplify the deployment process for users. These will be customisable to suit a variety of environments.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-9",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Leveraging DevOps and Automation:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-10",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Continuous Integration and Delivery (CI/CD):</strong> Integrate automated testing into the CI/CD system so Openchip can adapt and respond to changing cloud ecosystems.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-11",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>GitOps:</strong> Embrace GitOps principles by managing infrastructure and application configurations declaratively in Git. This ensures traceability, auditability, and version control, simplifying rollback and disaster recovery.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-12",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Implementing Fleet Management Frameworks:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-13",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Fleet Management Integration:</strong> Work out integrations with popular fleet management frameworks and leverage my experience in Kubernetes/Docker to ensure their compatibility.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-14",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Leverage Cloud-Native Technologies:</strong> Since Openchip will be delivering to the cloud, they should leverage cloud-native services such as AWS Fleet Manager/Azure Automanage and Google's Fleet Management.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-15",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Utilising My Existing Skills and Experiences:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-16",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Code Institute Skills:</strong> Leverage my proficiency in Python and related technologies (API dev) to develop and maintain APIs.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-17",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Leverage Communication at Trinity College:</strong> I would make sure I adopt standard API practices so that the new cloud ecosystem will be seamlessly delivered and deployed in the company.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-5-18",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Expected Outcomes</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
    ],
    "layoutRole": "halfCard",
  },
  {
    "id": "tpl-cloud-digital-page-card-6",
    "type": "page-card",
    "span": 6,
    "fontSize": "base",
    "title": "Cloud Security",
    "content": "/images/vpd/2596BE_2.webp",
    "showCoverImage": true,
    "mediaType": "image",
    "description": "<strong>Addressing Cloud Security and Compliance Concerns</strong>",
    "height": 368,
    "detailedBlocks": [
      {
        "id": "tpl-cloud-digital-nested-6-0",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "I understand that for Openchip, as a leading developer of high-performance accelerator chips, ensuring the security and compliance of cloud applications and infrastructure is paramount. Protecting sensitive data, maintaining the integrity of systems, and adhering to relevant compliance standards (e.g., GDPR, industry-specific regulations) are critical to maintaining customer trust and achieving sustainable growth.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-1",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Here is how my solution would look like</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-2",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Implement a Robust Identity and Access Management (IAM) System:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-3",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Data Encryption and Protection:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-4",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Encryption at Rest:</strong> Encrypt all sensitive data at rest using industry-standard encryption algorithms (AES-256 or similar). I will leverage cloud provider's encryption services (e.g., AWS KMS, Azure Key Vault, Google Cloud KMS) for secure key management.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-5",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Encryption in Transit:</strong> All data transmitted between systems and services will be encrypted using TLS/SSL. I will enforce HTTPS for web applications and APIs and utilise secure protocols like SSH for remote access.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-6",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Network Security and Segmentation:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-7",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Network Segmentation:</strong> Segment the network into isolated zones based on functionality and security requirements. I will also use microsegmentation techniques to isolate individual applications and services, minimising the impact of potential breaches.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-8",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Firewall Management:</strong> Deploy and configure firewalls to control network traffic between zones and prevent unauthorised access. I will use a combination of network firewalls and web application firewalls (WAFs) to protect against a wide range of threats.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-9",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Security Monitoring and Threat Detection:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-10",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Security Information and Event Management (SIEM):</strong> Implement a SIEM system to collect and analyse security logs from all systems and services. I will use the SIEM to detect suspicious activity, identify potential threats, and trigger automated alerts.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-11",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Intrusion Detection and Prevention Systems (IDS/IPS):</strong> Deploy IDS/IPS solutions to monitor network traffic for malicious activity and automatically block or mitigate threats. I would leverage both host-based and network-based IDS/IPS systems for comprehensive coverage.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-12",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Compliance Automation and Continuous Monitoring:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-13",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Fleet Management Integration:</strong> Work out integrations with popular fleet management frameworks and leverage my experience in Kubernetes/Docker to ensure their compatibility.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-14",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Leverage Cloud-Native Technologies:</strong> Since Openchip will be delivering to the cloud, they should leverage cloud-native services such as AWS Fleet Manager/Azure Automanage and Google's Fleet Management.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-15",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Utilising My Existing Skills and Experiences:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-16",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Compliance-as-Code:</strong> Automate compliance checks using configuration management tools like Chef, Puppet, or Ansible. I will define compliance rules as code and automatically verify that systems are compliant with relevant standards.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-17",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Compliance Dashboards:</strong> Create compliance dashboards that provide real-time visibility into the compliance posture of the cloud environment. I will use these dashboards to track compliance metrics, identify gaps, and prioritise remediation efforts.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-18",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Security Training and Awareness:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-19",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Security Awareness Training:</strong> Conduct regular security awareness training for all employees to educate them about common threats and best practices for protecting sensitive data.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-20",
        "type": "text",
        "span": 12,
        "height": 200,
        "content":
          "<strong>Phishing Simulations:</strong> Conduct phishing simulations to test employee awareness and identify areas for improvement. I will use the results of these simulations to tailor training programs and improve overall security posture.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-21",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Collaboration and Knowledge Sharing:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-22",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Incident Response Plan:</strong> I will establish guidelines to respond when sensitive information has been compromised.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-23",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Share security information across divisions of the company</strong>: The plan should be tailored for each division so all staff are aware of potential threats.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-24",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Leveraging My Existing Skills and Experiences:</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-25",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>Code Institute Experience and Vulnerabilities:</strong> Showcasing past vulnerability testing will improve the company\u2019s perception of your security abilities.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-26",
        "type": "text",
        "span": 12,
        "height": 96,
        "content":
          "<strong>MedTank Experience in AI Microservices:</strong> My experience integrating data to deliver AI driven content safety will promote positive security.",
        "fontSize": "base",
        "layoutRole": "section",
      },
      {
        "id": "tpl-cloud-digital-nested-6-27",
        "type": "text",
        "span": 12,
        "height": 96,
        "content": "<strong>Expected Outcomes</strong>",
        "fontSize": "base",
        "layoutRole": "section",
      },
    ],
    "layoutRole": "halfCard",
  },
  {
    "id": "tpl-cloud-digital-text-7",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "30 - 60 - 90 days",
    "content":
      "As I integrate into the Junior Cloud Engineer position at Openchip, I'm eager to make an immediate and lasting effect. This strategy outlines my objectives for the first 90 days, along with how I'll use my abilities and experience to advance Openchip's objective of spearheading European digital sovereignty in line with the company's objectives.",
    "templateSectionTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-8",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "30 days",
    "portfolioEntryTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-9",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Immersion and Assessment</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-10",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "During the first month, my focus will be on learning the ropes and setting the stage for future contributions.",
    "layoutRole": "quote",
  },
  {
    "id": "tpl-cloud-digital-text-11",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Goals</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-12",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "<ol><li><strong>Deep Dive into Openchip's Technology Stack:</strong> Gain a comprehensive understanding of Openchip's existing cloud infrastructure, development processes, and current projects, especially those related to RISC-V accelerators.</li><li><strong>Meet Key Stakeholders:</strong> Build relationships with team members, key partners, and stakeholders to foster collaboration and open communication.</li><li><strong>Understand Priorities and Challenges:</strong> Identify the most pressing challenges and priorities for the cloud engineering team, particularly those related to cloud orchestration, observability, and security.</li><li><strong>Familiarise Myself with Openchip's Business Model</strong>: I will take a proactive approach in understanding Openchip's 56 partners with whom they are digitally transforming, so as to deliver as fast and efficiently as possible.</li></ol>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-13",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Actions</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-14",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "<ol><li>I will dive into technical documentation, architecture diagrams, and codebase to understand the existing system architecture.</li><li>Schedule one-on-one meetings with team members, managers, and partner contacts to clarify roles, responsibilities, and communication channels.</li><li>I will participate in team meetings, sprint planning sessions, and code reviews to get a feel for the development workflow.</li><li>I will research industry best practices for cloud security and automation in the HPC and AI/ML space. This will give me an additional understanding of the domain that Openchip is trying to digitally transform.</li></ol>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-15",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "60 days",
    "portfolioEntryTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-16",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Contribution and Optimisation</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-17",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "During the second month, I will begin actively contributing to the team and identifying opportunities for optimisation.",
    "layoutRole": "quote",
  },
  {
    "id": "tpl-cloud-digital-text-18",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Goals</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-19",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "<ol><li><strong>Address High-Priority Tasks: </strong>Take ownership of specific tasks or projects aligned with Openchip's immediate needs, such as developing Kubernetes Device Plugins, implementing monitoring solutions, or automating security checks.</li><li><strong>Identify Optimisation Opportunities: </strong>Propose and implement solutions to improve system performance, scalability, security, or reliability.</li><li><strong>Enhance Existing Infrastructure: </strong>Propose new methods in securing the cloud and also create new documentation to help the team learn and grow.</li></ol>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-20",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Actions</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-21",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "<ol><li>I will work on refactoring high-priority code and work more methodically after receiving feedback from other team members. I will also incorporate automated tests and follow code architecture.</li><li>I will deploy monitoring and alerting systems to detect performance bottlenecks.</li><li>I propose automating infrastructure management using Terraform or Azure Resource Manager templates.</li><li>I will ensure a strong cyber posture in compliance with internal policies and external standards.</li></ol>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-22",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "90 days",
    "portfolioEntryTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-23",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "How does the company add value to me?",
    "templateSectionTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-24",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Opportunity to Contribute to a Meaningful Mission:</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-25",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "The opportunity to work on projects that directly contribute to Openchip's mission excites me to lead the development of the next generation of European chips, as well as have a tremendous positive impact on societal advancement.<br><em>These are some of the best goals of tech that I want to enable by enabling cloud tech. In particular, delivering high-performance and energy-efficient accelerators, is essential for the European digital transformation so I have a personal connection and goal to fulfill.</em>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-26",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Exposure to a Diverse Technology Stack</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-27",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "I am aware that in this company, I will be able to dive into AWS, Microsoft Azure tools - which is perfect for digital transformation. Also, these tools are cloud platforms and I am very familiar with them. This means I can deliver and create a unique digital edge that will empower my growth as the company grows",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-28",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Supportive Culture</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-29",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "The listed soft skills like collaborative, communicative, proactive, self-aware are how I operate on a consistent basis. Also Openchip and Software Technologies S.L., highlights their belief in a diverse and inclusive team, so I want my team know I am looking to develop my own leadership skills by integrating myself into a group with different skillsets. I strongly desire a world where everyone is valued regardless of race, gender, ethnicity, sexual orientation and gender identity.",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-30",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "How do I fit in with the culture of the company?",
    "templateSectionTitle": true,
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-31",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Autonomous Development:</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-32",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Openchip's dedication to innovation aligns perfectly with my passion for creating and implementing cutting edge cloud solutions. My experiences in developing cloud ML models at Trinity College reflects Openchip's need to develop AI applications. I was able to reduce time for ML predictions by 35% with the use of cloud tools.",
    "layoutRole": "quote",
  },
  {
    "id": "tpl-cloud-digital-text-33",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Teamwork and Collaboration:</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-34",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "For more than thirty years the GTD have delivered communication for the world's best, and it tells me that I will be working in a work culture where teamwork is a top priority. Openchip wants those who can communicate well and deliver, and these are great values I have.",
    "layoutRole": "quote",
  },
  {
    "id": "tpl-cloud-digital-text-35",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Problem-Solving and Can-Do Attitude:</strong>",
    "layoutRole": "section",
  },
  {
    "id": "tpl-cloud-digital-text-36",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "I want to implement the 'CAN DO' attitude at Openchip, since this is what my colleagues constantly tell me. I constantly resolve challenges at every point in time. This is a mindset I hope to deliver to the team during project development.",
    "layoutRole": "quote",
  },
  {
    "id": "tpl-cloud-digital-text-37",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Conclusion",
    "content":
      "I am excited by the opportunity to contribute to Openchip's mission and confident that my skills, proactive approach, and alignment with your values make me an ideal fit. I am eager to join your team and help drive innovation, build strong partnerships, and accelerate Europe's digital transformation journey. I look forward to discussing how I can add value to the company.",
    "templateSectionTitle": true,
    "layoutRole": "section",
  },
] as PortfolioItem[];
