import type { PortfolioItem } from "@/types";

/** V1 base placeholder (Role @ Company) converted to portfolio-grid blocks. */
export const GENERAL_PITCH_COVER_URL = "https://storage.googleapis.com/unimadai-media-files/HbxYuhZxAl/cover-picture/SHaki.webp";

export const GENERAL_PITCH_DETAILED_BLOCKS: PortfolioItem[] = [
  {
    "id": "tpl-general-text-0",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Value Proposition Document",
    "content":
      "State your objective clearly \u2013 what role you're aiming for and why you're interested in being an active contributor for the role and the company.<br><br><strong>Example:</strong> \"With over 5 years of experience in enhancing brand visibility and engagement through targeted strategies, I am seeking the role of Marketing Manager at \\[Company Name\\] to leverage my skills in an environment that prioritises growth and creativity. Here's a document explaining why I am a good fit for the role?",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-1",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "How do I add value to the company?",
    "content":
      "The company is hiring you to solve a problem they are facing. Understand the problem for which the company is hiring you and try giving out solutions or frameworks for the same. This is how you add value to the company.",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-2",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Problem Statements",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-page-card-3",
    "type": "page-card",
    "span": 6,
    "fontSize": "base",
    "title": "Problem Statement 1",
    "content": "https://storage.googleapis.com/unimadai-media-files/HbxYuhZxAl/undefined/SHaki_5.png",
    "showCoverImage": true,
    "mediaType": "image",
    "description": "Describe the problem and your approach.",
    "height": 280,
    "detailedBlocks": [
      {
        "id": "tpl-general-sol-3",
        "type": "text",
        "span": 12,
        "title": "Solution",
        "content": "Outline your solution for this problem.",
        "fontSize": "base",
        "layoutRole": "section",
      },
    ],
  },
  {
    "id": "tpl-general-page-card-4",
    "type": "page-card",
    "span": 6,
    "fontSize": "base",
    "title": "Problem Statement 2",
    "content": "https://storage.googleapis.com/unimadai-media-files/HbxYuhZxAl/undefined/SHaki_6.png",
    "showCoverImage": true,
    "mediaType": "image",
    "description": "Describe the problem and your approach.",
    "height": 280,
    "detailedBlocks": [
      {
        "id": "tpl-general-sol-4",
        "type": "text",
        "span": 12,
        "title": "Solution",
        "content": "Outline your solution for this problem.",
        "fontSize": "base",
        "layoutRole": "section",
      },
    ],
  },
  {
    "id": "tpl-general-text-5",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "30-60-90 days",
    "content": "Here's everything you can expect from me in the first 30-60-90 days of me joining the company.",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-6",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "30 days",
    "portfolioEntryTitle": true,
  },
  {
    "id": "tpl-general-text-7",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Orientation &amp; Product Mastery</strong>",
  },
  {
    "id": "tpl-general-text-8",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "In my first 30 days, I'll be dedicating myself to these key areas:",
  },
  {
    "id": "tpl-general-text-9",
    "type": "text",
    "span": 6,
    "fontSize": "base",
    "title": "Key Point 1",
    "content": "Talk about the different things you'll achieve in your first month. Refer to the sample VPD to get a better understanding.",
    "layoutRole": "halfCard",
  },
  {
    "id": "tpl-general-text-10",
    "type": "text",
    "span": 6,
    "fontSize": "base",
    "title": "Key Point 2",
    "content": "Talk about the different things you'll achieve in your first month. Refer to the sample VPD to get a better understanding.",
    "layoutRole": "halfCard",
  },
  {
    "id": "tpl-general-text-11",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "60 days",
    "portfolioEntryTitle": true,
  },
  {
    "id": "tpl-general-text-12",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Execution &amp; Relationship Management</strong>",
  },
  {
    "id": "tpl-general-text-13",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "In my first 60 days, I'll be dedicating myself to these key areas:",
  },
  {
    "id": "tpl-general-text-14",
    "type": "text",
    "span": 6,
    "fontSize": "base",
    "title": "Key Point 1",
    "content":
      "Talk about the different things you'll achieve in your second month. Refer to the sample VPD to get a better understanding.",
    "layoutRole": "halfCard",
  },
  {
    "id": "tpl-general-text-15",
    "type": "text",
    "span": 6,
    "fontSize": "base",
    "title": "Key Point 1",
    "content":
      "Talk about the different things you'll achieve in your second month. Refer to the sample VPD to get a better understanding.",
    "layoutRole": "halfCard",
  },
  {
    "id": "tpl-general-text-16",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "90 days",
    "portfolioEntryTitle": true,
  },
  {
    "id": "tpl-general-text-17",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "<strong>Optimisation and Strategic Expansion</strong>",
  },
  {
    "id": "tpl-general-text-18",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "By my third month, I plan to demonstrate significant progress.",
  },
  {
    "id": "tpl-general-text-19",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "How does the company add value to me?",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-20",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Growth Opportunities",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-21",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Identify specific programs, training, or mentorship opportunities the company offers that align with your career growth plans.",
  },
  {
    "id": "tpl-general-text-22",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Example \u2014 The company's leadership development program that aligns with your aspiration to move into management roles.",
  },
  {
    "id": "tpl-general-text-23",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Example \u2014 Your advanced analytics training can deepen my data science abilities.",
  },
  {
    "id": "tpl-general-text-24",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Open Culture",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-25",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Discuss how the company's commitment to innovation and a culture of continuous learning can help you grow your skills and knowledge.",
  },
  {
    "id": "tpl-general-text-26",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Example \u2014 Your culture of continuous improvement matches my desire to always be learning.",
  },
  {
    "id": "tpl-general-text-27",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Example \u2014 Your regular hackathons are a great way for me to test and grow my coding skills.",
  },
  {
    "id": "tpl-general-text-28",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Community Networking",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-29",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Highlight how being part of the company can expand your professional network and connect you with industry leaders and innovators.",
  },
  {
    "id": "tpl-general-text-30",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Example \u2014 The company's industry conferences and events that offer networking opportunities with thought leaders.",
  },
  {
    "id": "tpl-general-text-31",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Example \u2014 Your partnership with top tech firms can introduce me to key industry contacts.",
  },
  {
    "id": "tpl-general-text-32",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "How do I fit in with the culture of the company?",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-33",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Values Fit",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-34",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Reflect on the company's core values and discuss how your personal and professional values align with them.",
  },
  {
    "id": "tpl-general-text-35",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Example \u2014 Your focus on sustainability mirrors my commitment to environmental advocacy.",
  },
  {
    "id": "tpl-general-text-36",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Example \u2014 Your emphasis on teamwork aligns with my belief in collaboration over competition.",
  },
  {
    "id": "tpl-general-text-37",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Collaboration",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-38",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Share your preferred teamwork and collaboration style and how it complements the company's approach to projects and problem-solving.",
  },
  {
    "id": "tpl-general-text-39",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Example \u2014 Your experience with cross-functional teams and how it prepares you to thrive in the company's collaborative environment.",
  },
  {
    "id": "tpl-general-text-40",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Example \u2014 Your experience with cross-functional teams and how it prepares you to thrive in the company's collaborative environment.",
  },
  {
    "id": "tpl-general-text-41",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Adaptability",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-42",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Describe how you adapt to different company cultures and dynamics, emphasising your flexibility and eagerness to be part of the company's community.",
  },
  {
    "id": "tpl-general-text-43",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content":
      "Example: Your successful integration into diverse team environments in past roles and how you plan to bring that adaptability to the new company.",
  },
  {
    "id": "tpl-general-text-44",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "title": "Conclusion",
    "templateSectionTitle": true,
  },
  {
    "id": "tpl-general-text-45",
    "type": "text",
    "span": 12,
    "fontSize": "base",
    "content": "Give a good CTA and a conclusion to your VPD. Refer to the sample templates for more details on this portion.",
  },
] as PortfolioItem[];
