"use server";

import { cookies } from "next/headers";

function getBackendUrl(): string {
  const url = process.env.NEXT_PUBLIC_BACKEND_URL;
  if (!url) {
    throw new Error("NEXT_PUBLIC_BACKEND_URL is not defined. Add it to your .env.local file.");
  }
  return url.replace(/\/+$/, "");
}

function looksLikeJwt(value: string): boolean {
  return /^ey[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]*$/.test(value.trim());
}

async function getAuthHeader(): Promise<string> {
  const cookieStore = await cookies();
  const token = cookieStore.get("_ut")?.value ?? cookieStore.get("__Host-ut")?.value;
  if (!token) throw new Error("Unauthorized");
  const scheme = looksLikeJwt(token) ? "Bearer" : "Token";
  return `${scheme} ${token}`;
}

export interface GenerateChatTitleResult {
  success: boolean;
  title?: string;
  error?: string;
}

/**
 * POST `/api/generate-unibot-chat-title/` — returns a short title generated by
 * Gemini from the user's first message. Title is persisted on `UnibotAdkSession`
 * when the session is registered; the client refreshes the session registry afterward.
 */
export async function generateUnibotChatTitleAction(userInput: string, sessionId: string): Promise<GenerateChatTitleResult> {
  try {
    const auth = await getAuthHeader();
    const res = await fetch(`${getBackendUrl()}/api/generate-unibot-chat-title/`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: auth,
      },
      cache: "no-store",
      body: JSON.stringify({ user_input: userInput, session_id: sessionId }),
    });

    const data = (await res.json().catch(() => ({}))) as {
      title?: string;
      error?: string;
      persisted?: boolean;
    };

    if (!res.ok) {
      return { success: false, error: data.error ?? `HTTP ${res.status}` };
    }

    const title = typeof data.title === "string" ? data.title.trim() : "";
    if (!title) {
      return { success: false, error: "Empty title from server" };
    }

    return { success: true, title };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}
